### ISSUE TITLE
Support `array` and `document` type

### ISSUE THREAD

**Issue by diegosperes** [diegosperes/fapi#1]
Add support to `array` and  `document` type, some example below.

```yaml

nestedField1:
  type: "document"
  stringField:
    type: "string"

nestedField2:
  type: "document"
  nestedField:
    type: "document"
    stringField:
      type: "string"

arrayField1:
  type: "array"
  signature: 
    type: "document"
    stringField:
      type: "string"
    dateField:
      type: "date"
      template: "2006-02-01"

arrayField2:
  type: "array"
  signature: 
    type: "int"
```
